function [StressOut, StressNode] = nodal_stresses(elnodes, stress);

StressOut = [elnodes(:,1), stress(:, [1:6, 10:12, 7:9])];

StressNode = elnodes(:,1);
StressNode(:,2) = (1+sqrt(3)/2)*StressOut(:,2) - 0.5*(StressOut(:,5) + ...
                  StressOut(:,11)) + (1-sqrt(3)/2)*StressOut(:,8);
StressNode(:,5) = (1+sqrt(3)/2)*StressOut(:,5) - 0.5*(StressOut(:,2) + ...
                  StressOut(:,8)) + (1-sqrt(3)/2)*StressOut(:,11);
StressNode(:,8) = (1+sqrt(3)/2)*StressOut(:,8) - 0.5*(StressOut(:,5) + ...
                  StressOut(:,11)) + (1-sqrt(3)/2)*StressOut(:,2);
StressNode(:,11) = (1+sqrt(3)/2)*StressOut(:,11) - 0.5*(StressOut(:,2) + ...
                  StressOut(:,8)) + (1-sqrt(3)/2)*StressOut(:,5);

StressNode(:,3) = (1+sqrt(3)/2)*StressOut(:,3) - 0.5*(StressOut(:,6) + ...
                  StressOut(:,12)) + (1-sqrt(3)/2)*StressOut(:,9);
StressNode(:,6) = (1+sqrt(3)/2)*StressOut(:,6) - 0.5*(StressOut(:,3) + ...
                  StressOut(:,9)) + (1-sqrt(3)/2)*StressOut(:,12);
StressNode(:,9) = (1+sqrt(3)/2)*StressOut(:,9) - 0.5*(StressOut(:,6) + ...
                  StressOut(:,12)) + (1-sqrt(3)/2)*StressOut(:,3);
StressNode(:,12) = (1+sqrt(3)/2)*StressOut(:,12) - 0.5*(StressOut(:,3) + ...
                  StressOut(:,9)) + (1-sqrt(3)/2)*StressOut(:,6);

StressNode(:,4) = (1+sqrt(3)/2)*StressOut(:,4) - 0.5*(StressOut(:,7) + ...
                  StressOut(:,13)) + (1-sqrt(3)/2)*StressOut(:,10);
StressNode(:,7) = (1+sqrt(3)/2)*StressOut(:,7) - 0.5*(StressOut(:,4) + ...
                  StressOut(:,10)) + (1-sqrt(3)/2)*StressOut(:,13);
StressNode(:,10) = (1+sqrt(3)/2)*StressOut(:,10) - 0.5*(StressOut(:,7) + ...
                  StressOut(:,13)) + (1-sqrt(3)/2)*StressOut(:,4);
StressNode(:,13) = (1+sqrt(3)/2)*StressOut(:,13) - 0.5*(StressOut(:,4) + ...
                  StressOut(:,10)) + (1-sqrt(3)/2)*StressOut(:,7);
